import { Tag } from 'model';

export interface ISock {
  id: string;
  name: string;
  tags: Tag[];
  sizes: string[];
  colors: string[];
  descriptions: string[];
  amount: number;
}

export const SOCKS: ISock[] = [
  {
    id: 'm01',
    name: 'Skarpety Męskie',
    tags: [Tag.Men],
    sizes: ['38-40', '41-43', '44-46'],
    colors: [
      'Biały',
      'Czarny',
      'Popiel',
      'Stalowy',
      'Jeans',
      'Ciemnoniebieski',
      'Grafit',
      'Beżowy',
    ],
    descriptions: [
      'Wykonane z wysokiej jakości bawełny czesankowej',
      'Różne wzory',
      'Płaski szew',
      'Szeroki nieuciskający ściągacz',
    ],
    amount: 10,
  },
  {
    id: 'm02',
    name: 'Exclusive',
    tags: [Tag.Men],
    sizes: ['39-41', '42-46'],
    colors: [
      'Biały',
      'Czarny',
      'Popiel',
      'Stalowy',
      'Bronze',
      'Jeans',
      'Ciemnoniebieski',
      'Grafit',
      'Beżowy',
    ],
    descriptions: [
      'Perfekcyjnie pasują do garnituru',
      'Wykonane z wysokiej jakości bawełny czesankowej',
      'Prawdziwy komfort i elegancja',
      'Płaski szew',
      'Szeroki nieuciskający ściągacz',
    ],
    amount: 10,
  },
  {
    id: 'm03',
    name: 'Skarpety Męskie',
    tags: [Tag.Men],
    sizes: ['38-40', '41-43', '44-46'],
    colors: [
      'Biały',
      'Czarny',
      'Popiel',
      'Stalowy',
      'Jeans',
      'Ciemnoniebieski',
      'Grafit',
      'Beżowy',
    ],
    descriptions: [
      'Wykonane z wysokiej jakości bawełny czesankowej',
      'Różne wzory',
      'Płaski szew',
      'Szeroki nieuciskający ściągacz',
    ],
    amount: 10,
  },
  {
    id: 'm04',
    name: 'Skarpety Męskie',
    tags: [Tag.Men],
    sizes: ['38-40', '41-43', '44-46'],
    colors: ['Czarny'],
    descriptions: [
      'Wykonane z wysokiej jakości bawełny czesankowej',
      'Różne wzory',
      'Płaski szew',
      'Szeroki nieuciskający ściągacz',
    ],
    amount: 10,
  },
  {
    id: 'm08',
    name: 'Skarpety Męskie',
    tags: [Tag.Men],
    sizes: ['38-40', '41-43', '44-46'],
    colors: [],
    descriptions: [
      'Wykonane z wysokiej jakości bawełny czesankowej',
      'Różne wzory',
      'Płaski szew',
      'Szeroki nieuciskający ściągacz',
    ],
    amount: 10,
  },
  {
    id: 'm06',
    name: 'Skarpety Męskie',
    tags: [Tag.Men],
    sizes: ['38-40', '41-43', '44-46'],
    colors: ['Czarny'],
    descriptions: [
      'Wykonane z wysokiej jakości bawełny czesankowej',
      'Różne wzory',
      'Płaski szew',
      'Szeroki nieuciskający ściągacz',
    ],
    amount: 10,
  },
  {
    id: 'w01',
    name: 'Skarpety Damskie',
    tags: [Tag.Women, Tag.Youth],
    sizes: ['35-37', '38-40', '41-43'],
    colors: ['DOPISZ'],
    descriptions: [
      'Wykonane z wysokiej jakości bawełny czesankowej',
      'Płaski szew',
    ],
    amount: 10,
  },
  {
    id: 'w02',
    name: 'Skarpety Damskie',
    tags: [Tag.Women, Tag.Youth],
    sizes: ['35-37', '38-40', '41-43'],
    colors: [],
    descriptions: [
      'Wykonane z wysokiej jakości bawełny czesankowej',
      'Płaski szew',
    ],
    amount: 10,
  },
  {
    id: 'w03',
    name: 'Skarpety Damskie',
    tags: [Tag.Women],
    sizes: ['35-37', '38-40', '41-43'],
    colors: [],
    descriptions: [
      'Wykonane z wysokiej jakości bawełny czesankowej',
      'Płaski szew',
    ],
    amount: 10,
  },
  {
    id: 'w04',
    name: 'Skarpety Damskie',
    tags: [Tag.Women, Tag.Youth],
    sizes: ['35-37', '38-40', '41-43'],
    colors: [],
    descriptions: [
      'Wykonane z wysokiej jakości bawełny czesankowej',
      'Płaski szew',
    ],
    amount: 10,
  },
  {
    id: 'w05',
    name: 'Skarpety Damskie',
    tags: [Tag.Women, Tag.Youth],
    sizes: ['35-37', '38-40', '41-43'],
    colors: [],
    descriptions: [
      'Wykonane z wysokiej jakości bawełny czesankowej',
      'Płaski szew',
      'Dodatkowy ściągacz na śródstopiu zapewnia zwiększoną stabilizację skarpety',
    ],
    amount: 10,
  },
  {
    id: 'w06',
    name: 'Skarpety Damskie',
    tags: [Tag.Women, Tag.Youth],
    sizes: ['35-37', '38-40', '41-43'],
    colors: [],
    descriptions: [
      'Wykonane z wysokiej jakości bawełny czesankowej',
      'Płaski szew',
    ],
    amount: 10,
  },
  {
    id: 'bs01',
    name: 'Stopki Bambusowe',
    tags: [Tag.Bamboo, Tag.Short],
    sizes: ['35-37', '38-40', '41-43', '44-46'],
    colors: [
      'Biały',
      'Czarny',
      'Popiel',
      'Beżowy',
      'Grafit',
      'Ciemnoniebieski',
      'Stalowy',
    ],
    descriptions: [
      'Płaski szew',
      'Wykonane z wysokiej jakości przędzy bambusowej',
      'Dodatkowe jony srebra zwiększają właściwości przeciwpotne i przeciwbakteryjne',
    ],
    amount: 10,
  },
  {
    id: 'b01',
    name: 'Skarpety Bambusowe',
    tags: [Tag.Bamboo],
    sizes: ['38-40', '41-43', '44-46'],
    colors: [
      'Biały',
      'Czarny',
      'Popiel',
      'Beżowy',
      'Grafit',
      'Ciemnoniebieski',
      'Stalowy',
    ],
    descriptions: [
      'Płaski szew',
      'Wykonane z wysokiej jakości przędzy bambusowej',
      'Dodatkowe jony srebra zwiększają właściwości przeciwpotne i przeciwbakteryjne',
      'Szeroki nieuciskający ściągacz',
    ],
    amount: 10,
  },
  {
    id: 'bf01',
    name: 'Bambus Frotte',
    tags: [Tag.Bamboo, Tag.Frotte],
    sizes: ['38-40', '41-43', '44-46'],
    colors: [
      'Biały',
      'Czarny',
      'Popiel',
      'Beżowy',
      'Grafit',
      'Ciemnoniebieski',
      'Stalowy',
    ],
    descriptions: [
      'Płaski szew',
      'Wykonane z wysokiej jakości przędzy bambusowej',
      'Dodatkowe jony srebra zwiększają właściwości przeciwpotne i przeciwbakteryjne',
      'Szeroki nieuciskający ściągacz',
    ],
    amount: 5,
  },
  {
    id: 'k01',
    name: 'Stopki',
    tags: [Tag.Short],
    sizes: ['35-37', '38-40', '41-43', '44-46'],
    colors: [],
    descriptions: [],
    amount: 10,
  },
  {
    id: 'k02',
    name: 'Stopki',
    tags: [Tag.Short],
    sizes: ['35-37', '38-40', '41-43', '44-46'],
    colors: [],
    descriptions: ['Płaski szew'],
    amount: 10,
  },
  {
    id: 'k03',
    name: 'Stopki',
    tags: [Tag.Short],
    sizes: ['35-37', '38-40', '41-43', '44-46'],
    colors: [],
    descriptions: ['Płaski szew'],
    amount: 10,
  },
  {
    id: 'k04',
    name: 'Stopki',
    tags: [Tag.Short],
    sizes: ['35-37', '38-40', '41-43', '44-46'],
    colors: [
      'Biały',
      'Czarny',
      'Ciemnoniebieski',
      'Jeans',
      'Grafit',
      'Popiel',
      'Beżowy',
      'Oliwka',
      'Stalowy',
      'Róż',
      'Błenkit',
      'Seledyn',
      'Wrzos',
      'Łosoś',
    ],
    descriptions: ['Płaski szew'],
    amount: 10,
  },
  {
    id: 'stopki-truskawki',
    name: 'Stopki',
    tags: [Tag.Short],
    sizes: ['35-37', '38-40', '41-43', '44-46'],
    colors: [],
    descriptions: ['Płaski szew'],
    amount: 10,
  },
  {
    id: 'p01',
    name: 'Podkolanówki',
    tags: [Tag.UnderKnee, Tag.OverKnee],
    sizes: ['35-37', '38-40', '41-43'],
    colors: ['Czarny'],
    descriptions: [
      'Płaski szew',
      'Szeroki nieuciskający ściągacz',
      'Różne wzory',
    ],
    amount: 5,
  },
  {
    id: 'p02',
    name: 'Podkolanówki',
    tags: [Tag.UnderKnee, Tag.OverKnee],
    sizes: ['35-37', '38-40', '41-43', '44-46'],
    colors: [
      'Czarny',
      'Biały',
      'Popiel',
      'Beżowy',
      'Grafit',
      'Stalowy',
      'Jeans',
    ],
    descriptions: ['Płaski szew', 'Szeroki nieuciskający ściągacz'],
    amount: 5,
  },
  {
    id: 'p03',
    name: 'Above Knee Socks',
    tags: [Tag.UnderKnee, Tag.OverKnee],
    sizes: ['35-37', '38-40', '41-43', '44-46'],
    colors: [
      'Czarny',
      'Biały',
      'Popiel',
      'Beżowy',
      'Grafit',
      'Stalowy',
      'Jeans',
    ],
    descriptions: ['Płaski szew', 'Szeroki nieuciskający ściągacz'],
    amount: 5,
  },
  {
    id: 's01',
    name: 'Sport Socks',
    tags: [Tag.Sport],
    sizes: ['38-40', '41-43', '44-46'],
    colors: ['Różnorodne kolory'],
    descriptions: ['Długi sportowy ściągacz', 'Płaski szew', 'Różne wzory'],
    amount: 10,
  },
  {
    id: 's02',
    name: 'Sport Socks',
    tags: [Tag.Sport],
    sizes: ['38-40', '41-43', '44-46'],
    colors: [],
    descriptions: ['Długi sportowy ściągacz', 'Płaski szew', 'Różne wzory'],
    amount: 10,
  },
  {
    id: 's04',
    name: 'Sport 3/4 Socks',
    tags: [Tag.Sport],
    sizes: ['35-37', '38-40', '41-43', '44-46'],
    colors: [],
    descriptions: ['Płaski szew'],
    amount: 10,
  },
  {
    id: 's05',
    name: 'Sport 3/4 Socks',
    tags: [Tag.Sport],
    sizes: ['35-37', '38-40', '41-43', '44-46'],
    colors: [],
    descriptions: ['Płaski szew'],
    amount: 10,
  },
  {
    id: 'a02',
    name: 'Bezuciskowe bez gumki',
    tags: [Tag.NoPressure],
    sizes: ['38-40', '41-43', '44-46'],
    colors: [
      'Czarny',
      'Biały',
      'Popiel',
      'Stalowy',
      'Beżowy',
      'Ciemnoniebieski',
      'Jeans',
      'Grafit',
    ],
    descriptions: [
      'Idealny dla osób z problemami krążenia',
      'Płaski szew',
      'Bez gumki w ściągaczu',
    ],
    amount: 10,
  },
  {
    id: 'a03',
    name: 'Bezuciskowe',
    tags: [Tag.NoPressure, Tag.Frotte],
    sizes: ['38-40', '41-43', '44-46'],
    colors: [
      'Biały',
      'Popiel',
      'Czarny',
      'Stalowy',
      'Beżowy',
      'Jeans',
      'Ciemnoniebieski',
      'Grafit',
    ],
    descriptions: ['Idealny dla osób z problemami krążenia', 'Płaski szew'],
    amount: 5,
  },
  {
    id: 'fh01',
    name: 'Półfrotte',
    tags: [Tag.Frotte],
    sizes: ['38-40', '41-43', '44-46'],
    colors: [],
    descriptions: ['Idealne na jesień i zimę'],
    amount: 5,
  },
  {
    id: 'fh02',
    name: 'Półfrotte 3/4',
    tags: [Tag.Frotte],
    sizes: ['35-37', '38-40', '41-43'],
    colors: [],
    descriptions: ['Idealne na jesień i zimę', 'Płaski szew'],
    amount: 5,
  },
  {
    id: 'fh03',
    name: 'Półfrotte',
    tags: [Tag.Frotte],
    sizes: ['35-37', '38-40', '41-43'],
    colors: [],
    descriptions: ['Idealne na jesień i zimę'],
    amount: 5,
  },
  {
    id: 'f01',
    name: 'Frotte',
    tags: [Tag.Frotte],
    sizes: ['35-37', '38-40', '41-43'],
    colors: [],
    descriptions: ['Płaski szew'],
    amount: 5,
  },
  {
    id: 'f03',
    name: 'Frotte',
    tags: [Tag.Frotte],
    sizes: ['38-40', '41-43', '44-46'],
    colors: [],
    descriptions: ['Długi sportowy ściągacz', 'Płaski szew'],
    amount: 5,
  },
];
